# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaFalhaConexao.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_FalhaConexao(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: rgb(97, 47, 116);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 591, 41))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 110, 461, 61))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.label.setObjectName("label")
        self.botaoReconecta = QtWidgets.QPushButton(self.centralwidget)
        self.botaoReconecta.setGeometry(QtCore.QRect(60, 190, 151, 31))
        self.botaoReconecta.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);\n"
"width:300px;\n"
"height:100px;\n"
"border-radius: 10px;")
        self.botaoReconecta.setObjectName("botaoReconecta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Não foi possível conecar ao banco de dados  :("))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Tente: </p><p>Confira se o WAMP esá funcionando corretamente</p><p><br/></p><p><br/></p></body></html>"))
        self.botaoReconecta.setText(_translate("MainWindow", "Tentar novamente"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_FalhaConexao()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
