# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaSaque.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Saque(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: rgb(97, 47, 116);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(170, 289, 301, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.botaoSacarVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoSacarVoltar.setGeometry(QtCore.QRect(50, 409, 93, 28))
        self.botaoSacarVoltar.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);\n"
"width:300px;\n"
"height:100px;\n"
"border-radius: 10px;")
        self.botaoSacarVoltar.setObjectName("botaoSacarVoltar")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(170, 149, 301, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.botaoSacar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoSacar.setGeometry(QtCore.QRect(290, 250, 81, 28))
        self.botaoSacar.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);\n"
"width:300px;\n"
"height:100px;\n"
"border-radius: 10px;\n"
"font: 8pt \"Arial\";")
        self.botaoSacar.setObjectName("botaoSacar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 90, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 210, 161, 31))
        self.lineEdit_2.setStyleSheet("width:300px;\n"
"height:100px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 209, 31, 31))
        self.label_3.setStyleSheet("image: url(:/icones/trancarTransparente.png);")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 169, 51, 31))
        self.label_2.setStyleSheet("image: url(:/icones/dolar.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 170, 161, 31))
        self.lineEdit.setStyleSheet("width:300px;\n"
"height:100px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botaoSacarVoltar.setText(_translate("MainWindow", "Voltar"))
        self.botaoSacar.setText(_translate("MainWindow", "Sacar"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">NOOB BANK</span></p><p align=\"center\"><span style=\" font-size:12pt;\">ÁREA DE SAQUE</span></p></body></html>"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", " Senha"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", " R$"))
from icons import icones


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Saque()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
