# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaTransferencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Transferencia(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: rgb(97, 47, 116);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 91, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 251, 161, 31))
        self.lineEdit_2.setStyleSheet("width:300px;\n"
"height:100px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.botaoTransferenciaVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoTransferenciaVoltar.setGeometry(QtCore.QRect(50, 410, 93, 28))
        self.botaoTransferenciaVoltar.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);\n"
"width:300px;\n"
"height:100px;\n"
"border-radius: 10px;")
        self.botaoTransferenciaVoltar.setObjectName("botaoTransferenciaVoltar")
        self.botaoTransferir = QtWidgets.QPushButton(self.centralwidget)
        self.botaoTransferir.setGeometry(QtCore.QRect(290, 291, 81, 28))
        self.botaoTransferir.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);\n"
"width:300px;\n"
"height:100px;\n"
"border-radius: 10px;")
        self.botaoTransferir.setObjectName("botaoTransferir")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 171, 161, 31))
        self.lineEdit.setStyleSheet("width:300px;\n"
"height:100px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 250, 31, 31))
        self.label_3.setStyleSheet("image: url(:/icones/trancarTransparente.png);")
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(170, 330, 301, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(170, 150, 301, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 170, 51, 31))
        self.label_2.setStyleSheet("image: url(:/icones/dolar.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 209, 51, 31))
        self.label_4.setStyleSheet("image: url(:/icones/do-utilizadorTransparente.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 210, 161, 31))
        self.lineEdit_3.setStyleSheet("width:300px;\n"
"height:100px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">NOOB BANK</p><p align=\"center\">ÁREA DE TRANSFERÊNCIA</p></body></html>"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", " Senha"))
        self.botaoTransferenciaVoltar.setText(_translate("MainWindow", "Voltar"))
        self.botaoTransferir.setText(_translate("MainWindow", "Transferir"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", " R$"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", " Nº da conta"))
from icons import icones


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Transferencia()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
