# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaDeposito.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Deposito(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: rgb(97, 47, 116);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 91, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 211, 161, 31))
        self.lineEdit_2.setStyleSheet("width:300px;\n"
"height:100px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 170, 51, 31))
        self.label_2.setStyleSheet("image: url(:/icones/dolar.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.botaoDepositoVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoDepositoVoltar.setGeometry(QtCore.QRect(50, 410, 93, 28))
        self.botaoDepositoVoltar.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);\n"
"width:300px;\n"
"height:100px;\n"
"border-radius: 10px;")
        self.botaoDepositoVoltar.setObjectName("botaoDepositoVoltar")
        self.botaoDepositar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoDepositar.setGeometry(QtCore.QRect(290, 251, 81, 28))
        self.botaoDepositar.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);\n"
"width:300px;\n"
"height:100px;\n"
"border-radius: 10px;")
        self.botaoDepositar.setObjectName("botaoDepositar")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 171, 161, 31))
        self.lineEdit.setStyleSheet("width:300px;\n"
"height:100px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 210, 31, 31))
        self.label_3.setStyleSheet("image: url(:/icones/trancarTransparente.png);")
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(170, 290, 301, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(170, 150, 301, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">NOOB BANK</span></p><p align=\"center\"><span style=\" font-size:12pt;\">ÁREA DE DEPÓSITO</span></p></body></html>"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", " Senha"))
        self.botaoDepositoVoltar.setText(_translate("MainWindow", "Voltar"))
        self.botaoDepositar.setText(_translate("MainWindow", "Depositar"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", " R$"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
from icons import icones


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Deposito()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
