# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Cliente(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: rgb(97, 47, 116);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 81, 31))
        self.label.setStyleSheet("font: 14pt \"Arial\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 121, 31))
        self.label_2.setStyleSheet("font: 14pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 421, 41))
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 50, 641, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 51, 31))
        self.label_5.setStyleSheet("font: 14pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(240, 271, 381, 181))
        self.listWidget.setObjectName("listWidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 230, 231, 31))
        self.label_6.setStyleSheet("font: 14pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(450, 30, 51, 21))
        self.label_7.setStyleSheet("font: 12pt \"Arial\";")
        self.label_7.setObjectName("label_7")
        self.botaoUsuarioSacar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoUsuarioSacar.setGeometry(QtCore.QRect(490, 100, 111, 31))
        self.botaoUsuarioSacar.setStyleSheet("width:300px;\n"
"color: rgb(0, 0, 0);\n"
"height:100px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"\n"
"\n"
"")
        self.botaoUsuarioSacar.setObjectName("botaoUsuarioSacar")
        self.botaoUsuarioDepositar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoUsuarioDepositar.setGeometry(QtCore.QRect(490, 140, 111, 31))
        self.botaoUsuarioDepositar.setStyleSheet("width:300px;\n"
"color: rgb(0, 0, 0);\n"
"height:100px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.botaoUsuarioDepositar.setObjectName("botaoUsuarioDepositar")
        self.botaoUsuarioTransferir = QtWidgets.QPushButton(self.centralwidget)
        self.botaoUsuarioTransferir.setGeometry(QtCore.QRect(490, 180, 111, 31))
        self.botaoUsuarioTransferir.setStyleSheet("width:300px;\n"
"color: rgb(0, 0, 0);\n"
"height:100px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.botaoUsuarioTransferir.setObjectName("botaoUsuarioTransferir")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(430, 70, 16, 151))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(480, 70, 111, 21))
        self.label_9.setStyleSheet("font: 12pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 410, 93, 28))
        self.pushButton_2.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);\n"
"width:300px;\n"
"height:100px;\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(504, 20, 101, 31))
        self.label_8.setStyleSheet("font: 12pt \"Arial\";\n"
"width:300px;\n"
"height:100px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(100, 80, 321, 31))
        self.label_10.setStyleSheet("font: 12pt \"Arial\";\n"
"width:300px;\n"
"height:100px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(100, 130, 321, 31))
        self.label_11.setStyleSheet("font: 12pt \"Arial\";\n"
"width:300px;\n"
"height:100px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(150, 180, 271, 31))
        self.label_12.setStyleSheet("font: 12pt \"Arial\";\n"
"width:300px;\n"
"height:100px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">Nome:</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Conta Nº: </span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Bem-vindo(a), </span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Cpf:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Úlimas transações</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Saldo</p></body></html>"))
        self.botaoUsuarioSacar.setText(_translate("MainWindow", "Sacar"))
        self.botaoUsuarioDepositar.setText(_translate("MainWindow", "Depositar"))
        self.botaoUsuarioTransferir.setText(_translate("MainWindow", "Transfereir"))
        self.label_9.setText(_translate("MainWindow", "Operaçõess"))
        self.pushButton_2.setText(_translate("MainWindow", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Cliente()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
