# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Principal(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 504)
        MainWindow.setStyleSheet("background-color: rgb(97, 47, 116);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(170, 110, 301, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 130, 51, 31))
        self.label_2.setStyleSheet("image: url(:/icones/do-utilizadorTransparente.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 170, 31, 31))
        self.label_3.setStyleSheet("image: url(:/icones/trancarTransparente.png);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 131, 161, 31))
        self.lineEdit.setStyleSheet("width:300px;\n"
"height:100px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 171, 161, 31))
        self.lineEdit_2.setStyleSheet("width:300px;\n"
"height:100px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.botaoPrincipalEntrar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoPrincipalEntrar.setGeometry(QtCore.QRect(320, 220, 93, 28))
        self.botaoPrincipalEntrar.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);\n"
"width:300px;\n"
"height:100px;\n"
"border-radius: 10px;")
        self.botaoPrincipalEntrar.setObjectName("botaoPrincipalEntrar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 270, 201, 31))
        self.label_4.setStyleSheet("font: 10pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(170, 250, 301, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.botaoPrincipalCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoPrincipalCadastrar.setGeometry(QtCore.QRect(380, 270, 93, 28))
        self.botaoPrincipalCadastrar.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);\n"
"width:300px;\n"
"height:100px;\n"
"border-radius: 10px;")
        self.botaoPrincipalCadastrar.setObjectName("botaoPrincipalCadastrar")
        self.botaoPrincipalSair = QtWidgets.QPushButton(self.centralwidget)
        self.botaoPrincipalSair.setGeometry(QtCore.QRect(20, 430, 93, 28))
        self.botaoPrincipalSair.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);\n"
"width:300px;\n"
"height:100px;\n"
"border-radius: 10px;")
        self.botaoPrincipalSair.setObjectName("botaoPrincipalSair")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">NOOB BANK</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Cpf"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.botaoPrincipalEntrar.setText(_translate("MainWindow", "Entrar"))
        self.label_4.setText(_translate("MainWindow", "Não tem  conta? Crie uma!"))
        self.botaoPrincipalCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.botaoPrincipalSair.setText(_translate("MainWindow", "Sair"))
from icons import icones


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Principal()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
